version: "3.9"

services:
  mysql:
    build:
      target: mysql
      context: ./devops
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - "./data:/var/lib/mysql"
    mem_limit: 100M
  web:
    build:
      target: web
      context: ./devops
    ports:
      - "${API_PORT}:80"
    volumes:
      - ./core:/var/www/html
      - ./devops/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - core
    depends_on:
      - core
    mem_limit: 100M
  core:
    build:
      target: core
      context: ./devops
    volumes:
      - ./core:/var/www/html
    depends_on:
      - mysql
    mem_limit: 100M
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: frontend
    ports:
      - "${CLIENT_PORT}:3000"
    volumes:
      - ./frontend:/app
    mem_limit: 100M
